### ISSUE TITLE
关于密匙问题

### ISSUE THREAD

**Issue by Tokyonth** [goldsudo/PicEncryptApp#1]
你好，我想问一下那个密匙，只能设置0—1之间的数吗？可以任意数字密匙吗，我不懂那个算法，希望能回应我一下，感谢了，你这个项目给我很大帮助

**Comment by goldsudo** [comment]
> 你好，我想问一下那个密匙，只能设置0—1之间的数吗？可以任意数字密匙吗，我不懂那个算法，希望能回应我一下，感谢了，你这个项目给我很大帮助

在我这份代码里，必须要0-1之间，这个密钥是用来最为混沌序列的第一个元素来生成其余元素的，我选用的混动序列生成式的密钥要求是0-1之间，如果选用别的混沌序列生成式的话就不一定非要0-1之间了噢。
混沌序列其实就是一个伪随机数序列，只要初值相同，剩下的元素就一模一样，所以可以用来加密后的解密还原。

**Comment by Tokyonth** [comment]
好的，谢谢，我把整数转换了小数，算是临时解决方案了
